Traceback (most recent call last):
  File "/home/user/Desktop/Python-Pereverzev/mod5/tests/test_redirect.py", line 24, in test_stderr
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
